### ISSUE TITLE
Option to not push/tag a release.

### ISSUE THREAD

**Issue by cpojer** [kittens/lerna#106]
On Jest we currently have a more involved release and push process. We are publishing more than just `packages/` and we are landing through our Facebook sync scripts. An option to avoid commit and pushing a diff would be great.

**Comment by thejameskyle** [comment]
To be clear you *do* want to publish to npm though right?

**Comment by cpojer** [comment]
Yes, I'd like to publish to npm (that's the point!) but I don't want to tag the release version with the commit because I have to amend the commit with other changes + I don't land the commit through `git push`.

**Comment by thejameskyle** [comment]
Okay, I can probably add a `--no-commit` flag pretty fast.

**Comment by cpojer** [comment]
I think either leaving the changes unstaged or committed but not pushed is fine :)
