### ISSUE TITLE
Prepublish

### ISSUE THREAD

**Issue by natew** [kittens/lerna#13]
I'm exploring converting a project to Lerna, it was based on Babel's old script system.

One thing I added was some tasks before publish depending on the package. Like we have a webpack that builds a production build before publishing in some packages.

Not sure if that exists here already? Some way to have certain packages run things before they publish?

**Comment by natew** [comment]
Edit: testing out with regular `npm prepublish`

**Comment by RickWong** [comment]
I believe it's already in master: https://github.com/kittens/lerna/blob/2dddce0c8f1550578b1042e65fbccc7d22844d7f/lib%2Fcommands%2Fpublish.js#L148-L152

**Comment by natew** [comment]
@RickWong that looks perfect, thank you
