### ISSUE TITLE
Should changed packages include cross-depencies?

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#27]
Right now when publishing a new version we:

1. Find all the changed packages by checking their diffs. [ref](https://github.com/kittens/lerna/blob/master/lib/commands/updated.js#L49-L54)
1. Cross check these "changed packages" for cross-deps and update them in `package.json`. [ref](https://github.com/kittens/lerna/blob/master/lib/commands/publish.js#L83-L104)
1. However, we don't update cross-dependencies outside of the original changed packages. ([ref1](https://github.com/kittens/lerna/blob/master/lib/commands/publish.js#L94-L95), [ref2](https://github.com/kittens/lerna/blob/master/lib/commands/publish.js#L88-L89))

I feel like this will cause issues with major versions. Because we're relying on npm's `^x.x.x` version matching for minor and patch versions outside of the changed packages.

**Comment by hzoo** [comment]
Yeah I think you're right on that.
Could we do that only if it's a major version change? Thats kinda what `FORCE_VERSION` does (but it would update all packages).

**Comment by thejameskyle** [comment]
Only doing it on major versions sounds like the best solution. The question is if we recursively look up changed packages or bump them all.

I'm concerned about how this would interact with #20

**Comment by thejameskyle** [comment]
Fixed in 2.0.0-beta.4
