### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#28]
Testing is like... really hard and stuff.

We should test though, because it's really hard to make changes on this repo with confidence.

**Comment by dendril** [comment]
When do you plan to consider an alpha version of master? I could try it with the project I'm running behind a private repo.

**Comment by hzoo** [comment]
Yeah we could just do a prerelease of master

**Comment by hzoo** [comment]
@thejameskyle, is a prelease good for now? We can publish `2.0.0-rc.1` or w.e to the prerelease dist tag or something else

**Comment by thejameskyle** [comment]
Yeah lets do a prerelease

**Comment by hzoo** [comment]
Ok - `2.0.0-rc.0`? What dist tag is good to you - `next` or `prerelease`

**Comment by dendril** [comment]
`2.0.0-rc1`

**Comment by hzoo** [comment]
Yeah I thought that too? Any ideas on https://github.com/babel/babel-eslint/issues/251?

**Comment by dendril** [comment]
hahahaha that issue is fun! 

Use `.x` if that makes everyones happy, personally I'm not using `^x.y.z-something` for serious things, always installing fixed versions if I want to play with it.

Please do that soon!! :+1:

**Comment by hzoo** [comment]
Ok in case we forget what the release was - I released the current master as `2.0.0-dev.05e9f0a` (didn't make any tags in git or anything). you can do `npm i lerna@prerelease` or the specific version

**Comment by thejameskyle** [comment]
> ***Deleted all the unrelated comments about publishing a release so that this issue can focus on testing.***

**Comment by thejameskyle** [comment]
I did this
