### ISSUE TITLE
lerna diff

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#41]
Whenever I run `lerna updated` and find something I didn't expect in there I immediately want to see the diff. It would be great if lerna could easily show me that.

```sh
$ lerna diff
$ lerna diff package-name
```

**Comment by hzoo** [comment]
So that could just alias to a git diff of that package? and there's https://github.com/stevemao/diff-so-fancy which I saw yesterday

**Comment by thejameskyle** [comment]
Yeah just `git diff` of `packages/` or `packages/{package-name}/` since the last release. I assume the following would just work:

```
lerna diff | diff-so-fancy
```

**Comment by thejameskyle** [comment]
Moving to #45
