### ISSUE TITLE
lerna.json

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#42]
Adding configuration and state to repos through CLI flags and separate files is going to get crazy. We should have one place for all of this in a repo.

```js
{
  "version": "1.0.0",
  "independent": false,
  "owners": [
    "kittens",
    "thejameskyle",
    "hzoo"
  ],
  // ...
}
```

**Comment by hzoo** [comment]
Configs is crazy too since every tool has one, but you're right it's probably better than everything else. At least this can replace the `VERSION` file so its same as before since this would include that as well?

**Comment by thejameskyle** [comment]
It could also just work on top of the package.json

**Comment by evocateur** [comment]
If you go the package.json route, I would suggest namespacing it under `lerna` or somesuch, analogous to the way babel and eslint (and others) do it.

```json
{
  "private": true,
  "lerna": {
    "version": "1.0.0",
    "independent": false,
    "owners": []
  },
  "devDependencies": {
    "foo": "^1.0.0"
  }
}
```

**Comment by hzoo** [comment]
Yeah for sure.

**Comment by thejameskyle** [comment]
Yup

**Comment by thejameskyle** [comment]
I'm going to do this next. I'm going to do a couple of things.

- Accept both `lerna.json` and `package.json#lerna` as config options
  - Defaulting to `lerna.json` in `lerna init` unless `package.json#lerna` is defined)
- If you run a command other than `lerna init` I'm going to check for the existence of a lerna config and if it does not exist, I'm going to tell the user to run `lerna init`
- In `lerna init` if a `VERSION` file exists, I'm going to move the version to the lerna config and remove the `VERSION` file.
- For now the only options that you can specify in a lerna config will be `version` and `independent`, everything else will come later.

Let me know if theres anything else you think I should do.

**Comment by thejameskyle** [comment]
Moving to #112

**Comment by matthewmueller** [comment]
Did this ever get added? 

> Accept both lerna.json and package.json#lerna as config options
