### ISSUE TITLE
lerna publish --only

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#43]
Not every change in a package needs to be published. For example if I just update a test I don't want to publish that. It might be cool if you could have a files array/glob of what you publish:

```sh
$ lerna publish --only package.json,README.md,src/**
```

Would work well with #42

**Comment by hzoo** [comment]
:+1: For sure, since we get a readme update and we probably don't need to publish just for that. (or even a test only change)?

**Comment by thejameskyle** [comment]
I'm thinking I want to do this in `lerna.json` instead:

```js
{
  "lerna": "2.0.0-beta.7",
  "version": "independent",
  "publishConfig": {
    "ignore": [
      "test/**"
    ]
  }
}
```

**Comment by thejameskyle** [comment]
#118
