### ISSUE TITLE
lerna init

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#47]
Rather than running the [init script](https://github.com/kittens/lerna/blob/master/lib/init.js) every single time, I think it'd be good to split that out into a `lerna init` command that did the same thing.

When you run any other command in a directory that hasn't been initialized using `lerna init` then it would just error.

This prevents weirdness when accidentally running lerna in a subdirectory which currently will just setup a new lerna repo.

**Comment by hzoo** [comment]
Alright, helps fix that use case and `lerna` init is explicit on what it does (although bootstrap/init sound a bit similar)

**Comment by thejameskyle** [comment]
`lerna new` maybe?

**Comment by hzoo** [comment]
Although... `npm init` is a convention people probably know about so maybe that's fine

**Comment by thejameskyle** [comment]
Plenty of other tools use `new` `ember/ng new`, `rails new`, etc

**Comment by hzoo** [comment]
:+1: Just wanted to think about whether having an `init/new/bootstrap` was cool
