### ISSUE TITLE
Changed Folder Structure

### ISSUE THREAD

**Issue by toddmoorega** [kittens/lerna#58]
Hi, I was trying lerna for a test project and it was all going fine until I decided to rename my modules in `packages`.

After I changed the name even if I delete node and npm and then reinstall lerna I get the follow:

```
There was a problem publishing.
Error: Command failed: git rev-list --tags --max-count=1
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
```

I was able to bootstrap and publish without any issues prior to folder renaming.

I have a .git folder. I've tried starting again with a fresh folder and project, restarting my computer...no luck, it's dead in the water. 

Is their some state being managed somewhere globally? I couldn't find anything that suggested their was, but it feels like something is amiss.

**Comment by gigabo** [comment]
Hi @toddmoorega.  I ran into that error this week.  Turns out there's [a fix in master](https://github.com/kittens/lerna/commit/204b94ce) that just hasn't been published yet.

My workaround was to just use `master` instead of `v1.1.0` for now.

**Comment by hzoo** [comment]
I'l just publish 1.1.1 (without uploading git tags to the repo) with that fix.

**Comment by toddmoorega** [comment]
Thanks, I suppose I should of tried that but it was getting late ;)

The master branch of lerna works fine, it's publishing like a boss again.

**Comment by hzoo** [comment]
FYI, We published 1.1.1

**Comment by toddmoorega** [comment]
:+1:

**Comment by hzoo** [comment]
I guess this can be close then?

**Comment by toddmoorega** [comment]
Yeah I think so
