### ISSUE TITLE
npmInstallInDir and linkDepedendenciesForPackage happen in wrong order

### ISSUE THREAD

**Issue by ianwremmel** [kittens/lerna#59]
It looks like https://github.com/kittens/lerna/commit/4ecfff5ac9facdf7bbb6f370f787f7d941a8b727 reversed the order of `npmInstallInDir` and `linkDependenciesForPackage` occur, so `lerna bootstrap` fails if the local packages have not previously been published to npm.

I'm happy to submit a PR to fix, but given how small that commit is, it seems like this was done intentionally.

**Comment by ianwremmel** [comment]
Interesting. it looks like the problem I had with local, non-published files was caused by naming an explicit version instead of including a "^" in the dependency's version specifier. I think I've fixed the issue that I had, but I'll leave this issue open until a maintainer takes a look because the current task ordering still seems problematic to me.

**Comment by thejameskyle** [comment]
The reason this was done previously is because npm was installing over the "linked" packages. I wasn't able to figure out why so I reversed the order.

I can see how this order is a problem for linking deps before they are published. I'll have to look into it more.

**Comment by thejameskyle** [comment]
Fixed in 2.0.0-beta.4
