### ISSUE TITLE
Should Lerna support Mercurial?

### ISSUE THREAD

**Issue by thejameskyle** [kittens/lerna#61]
One of the concerns about monorepos is that git doesn't scale well for massive repositories, and while there is lots of work being done to improve this. Today mercurial has much better support for it, companies like [Facebook](https://code.facebook.com/posts/218678814984400/scaling-mercurial-at-facebook/) and Google both use mercurial for large scale projects (@kittens you probably have insight on this). 

Do we want to consider dual-supporting both git and mercurial? I haven't used mercurial before, but based on some initial reading I don't think it'd be hard to abstract out our git operations that could support both.

**Comment by thejameskyle** [comment]
> We should wait for people to request since we aren't using it

Yeah that sounds good.

**Comment by kittens** [comment]
Any large company that uses a monorepo will already have developed solutions that solve this problem, and most of them wont even have it because of the way the codebases are architectured (only one version, `master`).

**Comment by thejameskyle** [comment]
Is it worth supporting otherwise then?

**Comment by onigoetz** [comment]
Hello, I would love the Mercurial support in Lerna, was anything done in that direction ?

**Comment by hzoo** [comment]
@onigoetz sorry no, we've already been pretty overloaded with other issues!

**Comment by onigoetz** [comment]
@hzoo Sure, no problem. I will experiment with Lerna in a project or two, would you be interested by a pull request for this ? (I can't promise anything, but if it answers my needs, I could take the time to contribute)
