### ISSUE TITLE
Using lerna as a library

### ISSUE THREAD

**Issue by thatjessicakelly** [kittens/lerna#74]
Hi, I'm trying to build a couple of tools on top of lerna, but I don't want to duplicate logic inside of lerna. Especially since it seems to be in flux right now and I don't want to keep updating things.

It would be cool if you could `require("lerna")` and call methods like `getPackagesDirectory()` or [`getPackages()`](https://github.com/kittens/lerna/blob/master/lib/utils/getPackages.js).

I can open a PR for this

**Comment by kittens** [comment]
This would be awesome, a PR would be appreciated!

**Comment by thatjessicakelly** [comment]
Is there anyway things could be changed to not rely on `process.cwd()`? That's kinda weird when using lerna as a normal node module.

**Comment by hzoo** [comment]
:+1: Yeah @thejameskyle mentioned he wanted to build tools on top of it as well

**Comment by thejameskyle** [comment]
Cool, moving discussion to that PR
