### ISSUE TITLE
Why does `lerna bootstrap` not `npm link`?

### ISSUE THREAD

**Issue by justin-calleja** [kittens/lerna#78]
Hi!

Can anyone explain why `lerna bootstrap` doesn't do `npm link`? Instead, I only see a pattern like this in, for example, /Users/justin/path/to/monorepo/packages/pkg2/node_modules/pkg1

```js
module.exports = require("/Users/justin/path/to/monorepo/packages/pkg1");
```

By `npm link`ing or by some other means, I'm trying to write a monorepo where each package has the following structure:

pkg1:
  index.js
  a/ 
  b/

I would like inter-dependent repos to be "installed" / linked in such a way as to be able to require/import files like so:

require('pkg1');
require('pkg1/a');
require('pkg1/b');

i.e. `lerna bootstrap`'s solution won't allow this, since only pkg1's main index.js file is exported:

```js
module.exports = require("/Users/justin/path/to/monorepo/packages/pkg1");
```

Any ideas? Thanks!

**Comment by kittens** [comment]
npm goes bananas when you have symlinks and try to `npm install` inside of it.

**Comment by justin-calleja** [comment]
Thanks @kittens !

Is there any way to work around this? Or is it in the pipeline to support requiring sub-paths in packages? (e.g. require('pkg1/es5/lib/somefile'))?

**Comment by justin-calleja** [comment]
The following is working for me (for now):

https://github.com/justin-calleja/lerna/commit/aedcd086a526a81ab9cdd36b0e3dc2749b33fc26

Not sure if this is what you want for this project, but if you want a PR, just let me know. Thanks!

**Comment by thejameskyle** [comment]
@justin-calleja I did this [previously](https://github.com/kittens/lerna/pull/34) and it caused issues so I had to [revert it](https://github.com/kittens/lerna/pull/35).

**Comment by thejameskyle** [comment]
Merging this ticket into https://github.com/kittens/lerna/issues/11 as a duplicate

**Comment by justin-calleja** [comment]
@thejameskyle thanks and sorry I didn't catch #11 when browsing through the issues.

Is the npm problem a bit involving to explain? I guess I'll come across it sooner or later if I continue linking.

Copying the dir structure or requiring all other files will suffer from having to re-run `lerna bootstrap` for every change in any package being depended upon. File watching might make this easier but… feels wrong.
