### ISSUE TITLE
What does it mean to "link together" packages?

### ISSUE THREAD

**Issue by callumlocke** [kittens/lerna#81]
> ### Bootstrap
>
> ```sh
> $ lerna bootstrap
> ```
>
> 1. Link together all packages that depend on each other.
> 2. `npm install` all other dependencies of each package.

What does the first point actually mean? Does it use `npm link`?

**Comment by thejameskyle** [comment]
It used to symlink packages, but thats actually a misnomer now as it instead creates a fake `package.json` and `index.js` file that point to the real location:

```js
module.exports = require('/real/path/to/package-name');
```

I need to rewrite the README
