### ISSUE TITLE
Private NPM Modules

### ISSUE THREAD

**Issue by toddmoorega** [kittens/lerna#82]
A little while back I tested lerna with private npm modules and _prima _facie__ it didn't seem to work.

Do you know if anyone has used it with private modules and whether or not this currently works? If not, I might look at creating a pull request to support them.

**Comment by thejameskyle** [comment]
There was a previous PR about it, I still don't understand the use case of some modules being private and some public

**Comment by toddmoorega** [comment]
I'll try it sometime in the next few weeks and I'll let you know what the use case might be. Overall though, you may be right, I just know that module scoping doesn't work, but, perhaps it isn't necessary.

**Comment by thejameskyle** [comment]
2.0.0-beta supports private packages

**Comment by christophercliff** [comment]
I'm getting an error on `lerna publish` if any of my packages are marked private in `beta.24`. Did plans change here?

**Comment by gigabo** [comment]
Hi @christophercliff, what is the error you're seeing?

We're able to `lerna publish` the [React Server](https://github.com/redfin/react-server) repo, which has a few private packages.

**Comment by christophercliff** [comment]
Trying to publish https://github.com/christophercliff/flatmarket with command:

```sh
./node_modules/.bin/lerna publish \
    --npm-tag=prerelease \
    --repo-version 3.0.0-beta.1
```

Error:

```
Publishing packages to npm...
Attempting to retry publishing flatmarket-example...
Error: Command failed: /bin/sh -c cd /flatmarket/packages/flatmarket-example && npm publish --tag lerna-temp
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /flatmarket/packages/flatmarket-example/npm-debug.log

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by gigabo** [comment]
Hmm... 😕 

Wonder why it's working for us, but not for you.  Doesn't look like it's the same as #286, but maybe similar?

**Comment by gigabo** [comment]
Well... this _was_ working for us.  Latest publish (on `2.0.0-beta.24`) failed. :(

@christophercliff - This was recently reported again in #303.  Will continue there.
