### ISSUE TITLE
Strategy for new versions

### ISSUE THREAD

**Issue by tmcw** [kittens/lerna#83]
I'm a little confused by the workflow lerna carves out for new major point versions of a library. In my example, [Turf](https://github.com/turfjs/turf) is, in 3.0.0, going to be a monorepo project instead of ~45 little repos. So right now I have a monorepo, with lots of newly-merged-in packages with 3.0.0 versions in their package.jsons, and [a branch](https://github.com/Turfjs/turf/tree/get-coord) with a 3.0.0 in the VERSION file.

What has worked sometimes and what I expected to be the workflow was that I'd run `lerna` and all of the 3.0.0 packages (which are not released) would link to each other, and that'd be it. But reading the code & diagnosing an issue today, I'm seeing that lerna [runs npm install _before_ it links dependencies](https://github.com/kittens/lerna/blob/master/lib/commands/bootstrap/linkDependencies.js#L31-L46), so it doesn't appear to be possible to reference unreleased versions in my repo. Is this the intentional design, and if so, how should `lerna`-based projects build major point releases?

**Comment by hzoo** [comment]
Related to https://github.com/kittens/lerna/issues/59?
We haven't done a major release yet either in babel since creating this so not sure yet.

**Comment by thejameskyle** [comment]
Fixed in 2.0.0-beta.4

**Comment by tmcw** [comment]
🙇  Thanks all!
